# Algebra Lineal

## Matriz
Una matriz A de mxn es un arreglo rectangular de mn numeros dispiestos en m renglones y n columnas. Los coeficientes de las variables x_1,x_2, x_3 en un sistema se pueden escribir como los elementos de una matriz A llamada **matriz de coeficientes** del sistema

Para poder trabajar con matrices o arrlegos, la libreria que se necesita es **Numpy**

In [2]:
import numpy as np

Si tenemos el sistema de ecuaciones

2x+4y+6z=18

4x+5y+6z=24

3x+y-2z=4

La matriz de coeficientes A seria

In [3]:
A=np.array(
    [[2,4,6],
    [4,5,6],
    [3,1,-2]]
)

In [4]:
A

array([[ 2,  4,  6],
       [ 4,  5,  6],
       [ 3,  1, -2]])

Entonces el vector de soluciones seria b

In [5]:
b=np.array([
    [18],
    [24],
    [4]
    ])

In [6]:
b

array([[18],
       [24],
       [ 4]])

El sistema entonces lo podemos representar como

**Ax=b**

Una matriz cuadrada es una atriz que tiene la misma cantidad de renglones y columnas 2x2, 3x3. Sin embargo tambien hay matrices mxn, como 3x2, 2x3, 2x4

### Matriz Nula
La matriz nula es una matriz donde los coeficientes son ceros

In [7]:
matriz_nula=np.zeros([3,3])

In [8]:
matriz_nula

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Matriz identidad
La matriz identidad es una mariz donde sus coeficientes son 1

In [9]:
matriz_identidad=np.ones([3,3])

In [10]:
matriz_identidad

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Igualdad de matrices
Dos matrices son iguales si:

1. Son del mismo tamaño
2. Las componentes correspondeintes son uguales

## Operaciones de matrices


### Suma de matrices
La suma de matrices A y B es la matriz mxn, la suma A+B se obtiene al sumar las componentes correspondientes de A y B

In [11]:
A+matriz_identidad

array([[ 3.,  5.,  7.],
       [ 5.,  6.,  7.],
       [ 4.,  2., -1.]])

### Teorema
Sean A, B y C tres matrices de mxn y sean alpha y beta dos escalares. Entonces:
1. A+0=A
2. 0A=0
3. A+B=B+A
4. (A+B)+C=A+(B+C)
5. alpha(A+B)=(alpha)A+(alpha)B
6. 1A=A
7. (alpha + beta)A=(alpha)A + (beta)A

### Multiplicacion de una matriz por un escalar
Si A es una matriz mxn y si alpha es un escalar, entonces la matriz mxn, (alpha)A es la matriz obtenida al multiplicar cada componente de A por alpha

In [12]:
A

array([[ 2,  4,  6],
       [ 4,  5,  6],
       [ 3,  1, -2]])

In [13]:
B=3*A
B

array([[ 6, 12, 18],
       [12, 15, 18],
       [ 9,  3, -6]])

### Teorema
Sean a, b y c tres vectores de dimension n y sea alpha un escalar. Entonces
1. a.0=0
2. a.b=b.a
3. a.(b+c)=a.b+a.c
4. ((alpha)a).b=alpha(a.b)

### Producto escalar
Para la multiplicacion entre matrices, debemos usar producto punto o la multiplicacion algebraica real

In [14]:
C=np.array([
    [1,2,3],
    [1,3,2],
    [3,2,1]
])

In [15]:
D=np.dot(A,C)
D

array([[24, 28, 20],
       [27, 35, 28],
       [-2,  5,  9]])

In [16]:
E=A@C
E

array([[24, 28, 20],
       [27, 35, 28],
       [-2,  5,  9]])

### Inversa de una matriz
Sea A y B dos matrices de nxn. Suponga que

AB=BA=I

Entonces B se llama la inversa de A y se denota por A^-1. Entonces se tiene

AA^-1=A^-1A=I

Si A tiene inversa, entonces se dice que A es invertible

In [17]:
A=np.array([
    [2,5],
    [1,3]
])

In [18]:
A_inversa=np.linalg.inv(A)
A_inversa

array([[ 3., -5.],
       [-1.,  2.]])

In [19]:
A@A_inversa

array([[1., 0.],
       [0., 1.]])

Veamos un ejemplo del uso de una matriz inversa para resolver un sistema de ecuaciones Ax=b

2x+4y+3z=6

y-z=-4

3x+5y+7z=7

In [20]:
A=np.array([
    [2,4,3],
    [0,1,-1],
    [3,5,7]
])
b=np.array([
    [6],
    [-4],
    [7]
])

In [21]:
A_inversa=np.linalg.inv(A)
A_inversa

array([[ 4.        , -4.33333333, -2.33333333],
       [-1.        ,  1.66666667,  0.66666667],
       [-1.        ,  0.66666667,  0.66666667]])

In [22]:
x=A_inversa@b
x

array([[25.],
       [-8.],
       [-4.]])

Entonces, tenemos que
x=25, y=-8 y z=-4

Sin embargo, exite una linea para resolver el sistema sin utilizar la inversa

In [23]:
solucion=np.linalg.solve(A,b)
solucion

array([[25.],
       [-8.],
       [-4.]])

### Transpuesta de una matriz
Sea A una matriz mxn. Entonces la transpuesta de A, que se escribe A^T, es la matriz nxm que se obtiene al intercambiar los renglones por las columnas de A

In [24]:
A

array([[ 2,  4,  3],
       [ 0,  1, -1],
       [ 3,  5,  7]])

In [25]:
A_transpuesta=A.T
A_transpuesta

array([[ 2,  0,  3],
       [ 4,  1,  5],
       [ 3, -1,  7]])

### Determinante


In [26]:
det_A=np.linalg.det(A)
det_A

np.float64(2.999999999999998)

## Atributos

Para conocer el mxn

In [27]:
A.shape

(3, 3)

Para saber la dimension

In [28]:
A.ndim

2

Para el tamaño de la matriz, es decir, la cantidad de elementos

In [29]:
A.size

9

Para conocer el tipo de datos dentro de la matriz

In [30]:
A.dtype

dtype('int64')

Para cambiar la distribucion de los elementos. Por ejemplo, convertir una fila larga de 12 numeros en una matriz de 4x3

In [31]:
R=np.array([
    [1,2,3],
    [4,5,6]
])

In [32]:
R.shape

(2, 3)

In [33]:
P=R.reshape(3,2)
P

array([[1, 2],
       [3, 4],
       [5, 6]])

Crear un arreglo donde se indica desde donde se empieza, el final y el incremento. No considera el numero final

In [34]:
e=np.arange(0,10,2)
e

array([0, 2, 4, 6, 8])

In [35]:
d=np.arange(1,10,3)
d

array([1, 4, 7])

Otra forma de crear un arreglo pero en lugar del incremento, es para dividir el segmento de forma equidistantes (Aqui si considera el numero final)

In [36]:
f=np.linspace(0,1,5)
f

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
g=np.linspace(1,5,12)
g

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

## Index y segmentacion

In [38]:
A

array([[ 2,  4,  3],
       [ 0,  1, -1],
       [ 3,  5,  7]])

In [39]:
A[0]

array([2, 4, 3])

In [40]:
A[-1]

array([3, 5, 7])

In [41]:
e

array([0, 2, 4, 6, 8])

In [42]:
e[1:4]

array([2, 4, 6])

In [43]:
e[:3]

array([0, 2, 4])

In [44]:
e[2:]

array([4, 6, 8])

Aplicado a matrices

In [45]:
A

array([[ 2,  4,  3],
       [ 0,  1, -1],
       [ 3,  5,  7]])

Para obtener la primer fila

In [46]:
A[0,:]

array([2, 4, 3])

Para obtener la segundacolumna

In [47]:
A[:,1]

array([4, 1, 5])

## Operaciones basicas en arreglos

In [48]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [49]:
a+b

array([5, 7, 9])

In [50]:
a-b

array([-3, -3, -3])

In [51]:
a*b

array([ 4, 10, 18])

In [52]:
a/b

array([0.25, 0.4 , 0.5 ])

// divide los numeros y redondea el resultado hacia abajo al numero entero mas cercano

In [53]:
a//b

array([0, 0, 0])

In [54]:
a**2

array([1, 4, 9])

% Devuelve el resto de dividi elemento a elemento entre dos arrays

In [55]:
a%b

array([1, 2, 3])

## Funciones agregadas

In [56]:
s=np.array([1,2,3,4,5])

In [57]:
np.sum(s)

np.int64(15)

In [58]:
np.mean(s)

np.float64(3.0)

In [59]:
np.median(s)

np.float64(3.0)

In [60]:
np.min(s)

np.int64(1)

In [61]:
np.max(s)

np.int64(5)

In [62]:
np.std(s)

np.float64(1.4142135623730951)

In [63]:
np.var(s)

np.float64(2.0)

cumsum es la suma acumulada

In [64]:
np.cumsum(s)

array([ 1,  3,  6, 10, 15])

cumprod es la multiplicacion acumulada

In [65]:
np.cumprod(s)

array([  1,   2,   6,  24, 120])

## Funciones estadisticas

In [66]:
np.mean(s)

np.float64(3.0)

In [67]:
np.median(s)

np.float64(3.0)

In [68]:
np.std(s)

np.float64(1.4142135623730951)

In [69]:
np.var(s)

np.float64(2.0)

In [70]:
np.argmin(s)


np.int64(0)

In [71]:
np.argmax(s)


np.int64(4)

In [72]:
np.percentile(s,25)


np.float64(2.0)

In [73]:
np.percentile(s,50)


np.float64(3.0)

In [74]:
np.percentile(s,75)

np.float64(4.0)

## Remodelacion y apilamiento
Reshaping and stacking

In [75]:
v=np.array([1,2,3,4,5,6])

In [76]:
v.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

vstack apila verticalmente

In [77]:
np.vstack([v,v])

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

hstack apila horizontalmente

In [78]:
np.hstack([v,v])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

column_stack apila los valores del arreglo en columnas, en este caso, dos veces porque utilizo v,v

In [79]:
np.column_stack((v,v))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6]])

concatenate se utiliza para unir dos o mas arreglos

In [80]:
np.concatenate((v,v))

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

## Dividir arreglos
Splitting Arrays

In [81]:
v

array([1, 2, 3, 4, 5, 6])

In [84]:
np.split(v,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [85]:
np.array_split(v,4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [86]:
w=np.array([
    [1,2,3],
    [4,5,6]
])

In [89]:
np.hsplit(w,3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [90]:
np.vsplit(w,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

## Operadores condicionales

In [91]:
v

array([1, 2, 3, 4, 5, 6])

In [92]:
v>3

array([False, False, False,  True,  True,  True])

In [94]:
v[v>3]

array([4, 5, 6])

In [96]:
np.where(v>3,'Yes','No')

array(['No', 'No', 'No', 'Yes', 'Yes', 'Yes'], dtype='<U3')

## Broadcasting


In [100]:
p=np.array([
    [1],
    [2],
    [3]
    ])
q=np.array([
    [10,20,30],
    [10,20,30],
    [10,20,30]
])

In [101]:
p+q

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

## Modulo Random

In [102]:
np.random.rand(2,3)

array([[0.35102074, 0.87205287, 0.43261498],
       [0.7838781 , 0.142358  , 0.19191677]])

In [111]:
np.random.randn(2,3)

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696]])

In [108]:
np.random.randint(1,10,(2,3))

array([[6, 7, 2],
       [7, 2, 2]])

In [107]:
np.random.choice([1,2,3,4],2)

array([1, 4])

In [109]:
np.random.seed(42)

## I/O Operations

In [113]:
np.save('arr.npy',a)

In [114]:
z=np.load('arr.npy')

In [115]:
np.savetxt('data.csw',a,delimiter=',')

In [116]:
z=np.loadtxt('data.csv',delimiter=',')

FileNotFoundError: data.csv not found.

## Useful functions

In [117]:
np.abs(a)

array([1, 2, 3])

In [118]:
np.round(a,2)

array([1, 2, 3])

In [119]:
np.clip(a,0,1)

array([1, 1, 1])

In [120]:
np.unique(a)

array([1, 2, 3])

In [121]:
np.sort(a)

array([1, 2, 3])

In [122]:
np.flip(a)

array([3, 2, 1])

In [123]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])